const exploreData = [
    {
        id: 1,
        image: '../assets/images/explore/e1.jpg',
        rated: "best rated",
        title: 'Tommy Hilifinger Bar',
        ratingNum: "5.0" ,
        ratingCount: '10 Ratings',
        cost: "5$-300$",
        category: 'Retaurant',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur non earum repudiandae ipsa reprehenderit quaerat.',
        status: 'close now',
        icon1: <i class="fa-solid fa-location-dot"></i>,
        icon2: <i class="fa-solid fa-arrow-up-from-bracket"></i>,
        icon3:  <i class="fa-regular fa-heart"></i>
    },
    {
        id: 2,
        image: '../assets/images/explore/e2.jpg',
        rated: "featured",
        title: 'Swiss inn resort',
        ratingNum: "4.5" ,
        ratingCount: '8 Ratings',
        cost: '50$-500$',
        category: 'Hotel',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur non earum repudiandae ipsa reprehenderit quaerat.',
        status: 'open now',
        icon1: <i class="fa-solid fa-location-dot"></i>,
        icon2: <i class="fa-solid fa-arrow-up-from-bracket"></i>,
        icon3:  <i class="fa-regular fa-heart"></i>
    },
    {
        id: 3,
        image: '../assets/images/explore/e3.jpg',
        rated: "best rated",
        title: 'Europe Tour',
        ratingNum: "5.0" ,
        ratingCount: '15 Ratings',
        cost: '5k$-10k$',
        category: 'Destination',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur non earum repudiandae ipsa reprehenderit quaerat.',
        status: 'close now',
        icon1: <i class="fa-solid fa-location-dot"></i>,
        icon2: <i class="fa-solid fa-arrow-up-from-bracket"></i>,
        icon3:  <i class="fa-regular fa-heart"></i>
    },
    {
        id: 4,
        image: '../assets/images/explore/e4.jpg',
        rated: "most viewed",
        title: 'Bunglow with swimming pool',
        ratingNum: "5.0" ,
        ratingCount: '10 Ratings',
        cost: '10k$-15k$',
        category: 'Real estate',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur non earum repudiandae ipsa reprehenderit quaerat.',
        status: 'close now',
        icon1: <i class="fa-solid fa-location-dot"></i>,
        icon2: <i class="fa-solid fa-arrow-up-from-bracket"></i>,
        icon3:  <i class="fa-regular fa-heart"></i>
    },
    {
        id: 5,
        image: '../assets/images/explore/e5.jpg',
        rated: "featured",
        title: 'vintage car expo',
        ratingNum: "4.2" ,
        ratingCount: '10 Ratings',
        cost: '500$-1200$',
        category: 'automation',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur non earum repudiandae ipsa reprehenderit quaerat.',
        status: 'open now',
        icon1: <i class="fa-solid fa-location-dot"></i>,
        icon2: <i class="fa-solid fa-arrow-up-from-bracket"></i>,
        icon3:  <i class="fa-regular fa-heart"></i>
    },
    {
        id: 6,
        image: '../assets/images/explore/e6.jpg',
        rated: "best rated",
        title: 'Thailand Tour',
        ratingNum: "5.0" ,
        ratingCount: '15 Ratings',
        cost: '5k$-10k$',
        category: 'destination',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur non earum repudiandae ipsa reprehenderit quaerat.',
        status: 'close now',
        icon1: <i class="fa-solid fa-location-dot"></i>,
        icon2: <i class="fa-solid fa-arrow-up-from-bracket"></i>,
        icon3:  <i class="fa-regular fa-heart"></i>
    },
]

export default exploreData;